### ISSUE TITLE
Support CompletableFuture

### ISSUE THREAD

**Issue by om26er** [google/desugar_jdk_libs#5]
With the release of Android Studio 4.0, I started looking into desugar_jdk_libs, however it seems that it's missing some of the APIs that we use in our [project](https://github.com/crossbario/autobahn-java/). Mainly `java.util.concurrent.CompletableFuture`, `java.util.concurrent.CompletionException` and `java.util.concurrent.Executor` are what we rely on. Since you guys have done much of the heavy lifting, I think it would be great if the above APIs were implemented as well.

[streamsupport](https://github.com/streamsupport/streamsupport) implements those APIs, so I believe its pretty doable.

**Comment by malloth** [comment]
I'd like to see this API as well. We use NATS in our Android project, but it's new version has switched to Java 8 and is using `java.util.concurrent.CompletableFuture`.

**Comment by eaftan** [comment]
Thank you for the suggestion. We are going to consolidate these issues into the Android issue tracker. Could you please refile this request here and include "[library desugar]" in the title? https://issuetracker.google.com/issues/new?component=317603&template=1018721
