### ISSUE TITLE
Support java.nio.channels ?

### ISSUE THREAD

**Issue by frist008** [google/desugar_jdk_libs#6]
With the release of Android Studio 4.0, I started looking into desugar_jdk_libs, however it seems that it's missing some of the APIs that we use in our project. For example java.nio.file.Files.newByteChannel, java.nio.channels.SeekableByteChannel. Since you guys have done much of the heavy lifting, I think it would be great if the above APIs were implemented as well.

**Comment by eaftan** [comment]
Thank you for the suggestion.  We are going to consolidate these issues into the Android issue tracker.  Could you please refile this request here and include "[library desugar]" in the title?  https://issuetracker.google.com/issues/new?component=317603&template=1018721
